flatpak install https://dl.flathub.org/repo/appstream/org.DolphinEmu.dolphin-emu.flatpakref
flatpak install https://dl.flathub.org/repo/appstream/net.kuribo64.melonDS.flatpakref
flatpak install https://dl.flathub.org/repo/appstream/org.duckstation.DuckStation.flatpakref
flatpak install https://dl.flathub.org/repo/appstream/org.libretro.RetroArch.flatpakref
flatpak install https://dl.flathub.org/repo/appstream/com.github.k4zmu2a.spacecadetpinball.flatpakref
flatpak install https://dl.flathub.org/repo/appstream/com.snes9x.Snes9x.flatpakref
flatpak install https://dl.flathub.org/repo/appstream/io.mgba.mGBA.flatpakref
flatpak install https://dl.flathub.org/repo/appstream/com.dosbox_x.DOSBox-X.flatpakref
flatpak install https://dl.flathub.org/repo/appstream/page.kramo.Cartridges.flatpakref
flatpak install https://dl.flathub.org/repo/appstream/io.github.sameboy.SameBoy.flatpakref
flatpak install https://dl.flathub.org/repo/appstream/io.github.snesrev.Zelda3.flatpakref
flatpak install https://dl.flathub.org/repo/appstream/io.github.fabiangreffrath.Doom.flatpakref
flatpak install https://dl.flathub.org/repo/appstream/dev.vencord.Vesktop.flatpakref
flatpak install https://dl.flathub.org/repo/appstream/com.obsproject.Studio.flatpakref
flatpak install https://dl.flathub.org/repo/appstream/org.videolan.VLC.flatpakref
